[package]
name = "daemon"
version = "0.1.0"
authors = ["FUJITA Tomonori <fujita.tomonori@gmail.com>"]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
tonic = "0.2"
bytes = "0.5"
prost = "0.6"
prost-types = "0.6"
prost-derive = "0.6"
tokio = { version = "0.2", features = ["full"] }
tokio-util = { version = "0.3" }
clap = "2.33"
futures = "0.3"
patricia_tree = "0.1"
regex = "1"
fnv = "1.0"
quinn = {git = "https://github.com/fujita/quinn.git",rev="f033275415617824fedb29bc459697919e11cf42"}
rcgen = "0.8"

proto = { path = "../proto" }

[build-dependencies]
tonic-build = "0.2"
