name: ci

on: [pull_request]

jobs:
  build:
    name: build container image
    runs-on: ubuntu-18.04
    steps:
      - uses: actions/checkout@master
      - name: build
        run: |
          docker build . -t rustybgp -f tests/integration/functional/Dockerfile
